config/routes.rb
Rails.application.routes.draw do
  get "house_expenses/account_cycle_summary" => "house_expenses#account_cycle_summary", :as => 'account_cycle_summary'
  resources :house_settings
  resources :house_account_cycles
  get 'sessions/new'

  resources :house_expense_per_tenants
  resources :house_expenses
  resources :house_expense_templates
  resources :recurring_frequencies
  resources :tenants
  resources :houses
  resources :sessions
  
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "house_expenses/update_fixed_expense/:fixed_expense_id" => "house_expenses#update_fixed_expense", :as => 'update_fixed_expense'
  get "house_expenses/edit_division_factor/:house_expense_id" => "house_expenses#edit_division_factor", :as => 'edit_division_factor'
  post "house_expenses/update_division_factor/:house_expense_id" => "house_expenses#update_division_factor", :as => 'update_division_factor'

  root 'houses#index'

end

app/models/house_expense.rb
class HouseExpense < ActiveRecord::Base
  belongs_to :tenant
  belongs_to :house_expense_cycle, :class_name => HouseAccountCycle, :foreign_key => 'house_account_cycle_id'
  has_many :house_expense_per_tenant, :class_name => HouseExpensePerTenant, :foreign_key => 'house_expense_id', :dependent => :destroy
  has_many :tenants, :through => :house_expense_per_tenant

  def self.is_all_fixed_expenses_updated?(house_id, house_account_cycle_id)
  	all_fixed_expenses_updated = true

  	fixed_templates = HouseExpenseTemplate.fixed_expenses_by_house_id(house_id)

  	fixed_template_ids = Array.new
  	fixed_template_map = {}

  	fixed_templates.each do |fixed_template|
  		fixed_template_ids.push(fixed_template.id)
  		fixed_template_map[fixed_template.id] = fixed_template
  	end

  	expenses = HouseExpense.where("house_id = ? and house_account_cycle_id = ? and house_expense_template_id in(?)", house_id, house_account_cycle_id, fixed_template_ids)

  	expenses.each do |expense|
  		fixed_template_map.delete(expense.house_expense_template_id)
  	end

  	if fixed_template_map.size != 0
  		fixed_template_map.each do |k, v|
  			puts "#{v.expense_name} is not updated for house_id: #{house_id} and account_cycle: #{house_account_cycle_id}"
  		end
  		all_fixed_expenses_updated = false
  	end

  	all_fixed_expenses_updated
  end

  def self.total_spending_by_tenants(house_id, account_cycle_id)
  	spending_by_tenants = HouseExpense.find_by_sql(["select t2.id as tenant_id ,COALESCE(t1.amount,0) as amount from(
													select tenant_id, round(sum(amount),2) amount from house_expenses
													where house_id = ? and house_account_cycle_id = ?
													group by tenant_id) t1
													full outer join
													(select id, 0 as amount from tenants) t2 on t1.tenant_id = t2.id",house_id,account_cycle_id])

  	spending_by_tenants
  end

  def self.get_expenses_for_current_cycle(house_id, house_account_cycle_id)
  	HouseExpense.where(:house_id => house_id, :house_account_cycle_id => house_account_cycle_id).order("house_expense_template_id nulls last, spent_date asc")
  end
end

app/controllers/house_expenses_controller.rb
class HouseExpensesController < ApplicationController
  #before_action :set_house_expense, only: [:show, :edit, :update, :destroy]

  # GET /house_expenses
  # GET /house_expenses.json
  def index
    @current_account_cycle = HouseAccountCycle.get_current_account_cycle(current_user.house_id)
    @fixed_expenses = HouseExpenseTemplate.fixed_expenses_not_paid_for_current_cycle(current_user.house_id)
    @house_expenses = HouseExpense.get_expenses_for_current_cycle(current_user.house_id, @current_account_cycle.id)
  end

  # GET /house_expenses/1
  # GET /house_expenses/1.json
  def show
  end

  # GET /house_expenses/new
  def new
    @house_expense = HouseExpense.new
    @house_expense.tenant_id = current_user.id
    @tenants = Tenant.where(:house_id => current_user.house_id)
  end

  # GET /house_expenses/1/edit
  def edit
  end

  # POST /house_expenses
  # POST /house_expenses.json
  def create
    @house_expense = HouseExpense.new(house_expense_params)
    @house_expense.house_expense_per_tenant.each do |per_tenant|
      per_tenant.amount = @house_expense.amount / @house_expense.house_expense_per_tenant.size
    end
    @house_expense.house_id = current_user.house_id
    account_cycle = HouseSetting.get_current_account_cycle_setting(current_user.house_id)
    @house_expense.house_account_cycle_id = account_cycle.setting_value
    respond_to do |format|
      if @house_expense.save
        format.html { redirect_to @house_expense, notice: 'House expense was successfully created.' }
        format.json { render :show, status: :created, location: @house_expense }
      else
        format.html { render :new }
        format.json { render json: @house_expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /house_expenses/1
  # PATCH/PUT /house_expenses/1.json
  def update
    respond_to do |format|
      if @house_expense.update(house_expense_params)
        format.html { redirect_to @house_expense, notice: 'House expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @house_expense }
      else
        format.html { render :edit }
        format.json { render json: @house_expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /house_expenses/1
  # DELETE /house_expenses/1.json
  def destroy
    @house_expense.destroy
    respond_to do |format|
      format.html { redirect_to house_expenses_url, notice: 'House expense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def update_fixed_expense
    expense_template = HouseExpenseTemplate.find(params[:fixed_expense_id])
    @house_expense = HouseExpense.new
    @house_expense.house_expense_template_id = expense_template.id
    @house_expense.expense_name = expense_template.expense_name
    @house_expense.amount = expense_template.default_amount
    @house_expense.tenant_id = current_user.id
    @tenants = Tenant.where(:house_id => current_user.house_id)
  end

  def edit_division_factor
    @current_account_cycle = HouseAccountCycle.get_current_account_cycle(current_user.house_id)
    @house_expense = get_house_expense_for_division_factor
  end

  def update_division_factor
    map = get_tenant_factor_map
    total_factor = 0
    map.each do |k, v|
      puts "k:#{k} v:#{v}"
      total_factor = total_factor + v.to_i
    end
    puts total_factor
    house_expense = get_house_expense_for_division_factor
    puts house_expense.amount
    house_expense.house_expense_per_tenant.each do |per_tenant|
      per_tenant.amount = (house_expense.amount / total_factor) * map[per_tenant.id.to_s].to_i
      puts per_tenant.amount
      per_tenant.division_factor = total_factor
      per_tenant.tenant_factor = map[per_tenant.id.to_s]
      per_tenant.save
    end

    respond_to do |format|
      format.html { redirect_to house_expenses_url }
    end
  end

  def account_cycle_summary
    @account_cycle = HouseAccountCycle.get_last_account_cycle(current_user.house_id)
    @total_summary = HouseAccountSummary.get_total_for_cycle(current_user.house_id, @account_cycle.id)
    @spendings = HouseAccountSummary.get_tenants_spendings(current_user.house_id, @account_cycle.id)
    @expenses = HouseAccountSummary.get_tenants_expenses(current_user.house_id, @account_cycle.id)
    @receivers = HouseAccountSummary.get_receivers(current_user.house_id, @account_cycle.id)
    @payers = HouseAccountSummary.get_payers(current_user.house_id, @account_cycle.id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_house_expense
      @house_expense = HouseExpense.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def house_expense_params
      params.require(:house_expense).permit(:tenant_id, :house_expense_template_id, :expense_name, :house_id, :amount, :spent_date, :tenant_ids => [])
    end

    def house_expense_per_tenant_params
      params.require(:house_expense).permit(:house_expense_per_tenant_ids)
    end

    def get_house_expense_for_division_factor
      house_expense = HouseExpense.find(params[:house_expense_id])
    end

    def get_tenant_factor_map
      map = Hash.new
      ids = params[:house_expense_per_tenants_ids]
      ids.each do |id|
        map[id] = params["house_expense_per_tenants_id" + id]
      end
      
      map
    end
end

app/helpers/house_expenses_helper.rb
module HouseExpensesHelper
end

app/views/house_expenses/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
<%= form_for(@house_expense, :html => {class: "form-horizontal"}) do |f| %>
  <% if @house_expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@house_expense.errors.count, "error") %> prohibited this house_expense from being saved:</h2>

      <ul>
      <% @house_expense.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :expense_name, class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.collection_select(:tenant_id, @tenants, :id, :name, {}, {:class => 'form-control'}) %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :expense_name, class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_field :expense_name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :amount, class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_field :amount, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :spent_date, class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.date_select :spent_date, {}, {:class => "form-control", :style => "display: inline;width: 32.5%;"} %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :tenant_ids, 'Tenants', class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.collection_check_boxes(:tenant_ids, @tenants, :id, :name) do |b| %>
        <%= b.label do%>
          <%=b.check_box + " " + b.text%>
        <%end%>
        <br/>
      <% end %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-3 col-sm-9">
      <%= f.submit 'Add expense', :class => "btn btn-default" %>
    </div>
  </div>
<% end %>
  </div>
</div>

app/views/house_expenses/account_cycle_summary.html.erb
<p id="notice"><%= notice %></p>

<div class="well well-sm">
  Summary of account cycle: <%= @account_cycle.from_date %> to <%= @account_cycle.to_date %>
</div>

<div class="panel panel-primary">
  <div class="panel-heading">Account summary breakdown</div>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Account Item</th>
        <th class="text-right">Amount(D)</th>
        <th class="text-right">Amount(C)</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%=@total_summary.account_item_description%></td>
        <td class="text-right"><%=@total_summary.amount%></td>
         <td class="text-right">&nbsp;</td>
      </tr>
      <tr>
        <td colspan="3">
      </tr>
      <% @expenses.each do |expense| %>
        <tr>
          <td><%=expense.account_item_description%> <%=expense.tenant.name%></td>
          <td class="text-right">&nbsp;</td>
          <td class="text-right"><%=expense.amount%></td>
        </tr>
      <% end %>
      <tr>
        <td colspan="3">
      </tr>
      <% @spendings.each do |spending| %>
        <tr>
          <td><%=spending.account_item_description%> <%=spending.tenant.name%></td>
          <td class="text-right"><%=spending.amount%></td>
          <td class="text-right"></td>
        </tr>
      <% end %>
      <tr>
        <td colspan="3">
      </tr>
      <% @receivers.each do |receiver| %>
        <tr>
          <td><%=receiver.account_item_description%> <%=receiver.to_tenant.name%> to <%=receiver.tenant.name%></td>
          <td class="text-right"><%=receiver.amount%></td>
          <td class="text-right"></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/house_expenses/edit.html.erb
<h1>Editing House Expense</h1>

<%= render 'form' %>

<%= link_to 'Show', @house_expense %> |
<%= link_to 'Back', house_expenses_path %>

app/views/house_expenses/edit_division_factor.html.erb
<p id="notice"><%= notice %></p>

<div class="well well-sm">
  Current account cycle: <%= @current_account_cycle.from_date %> to <%= @current_account_cycle.to_date %>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <%= form_tag("/house_expenses/update_division_factor/" + @house_expense.id.to_s) do |f| %>
  <% if @house_expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@house_expense.errors.count, "error") %> prohibited this house_expense from being saved:</h2>

      <ul>
      <% @house_expense.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <table class="table table-bordered">
    <tbody>
      <tr>
        <td>Expense</td>
        <td><%= @house_expense.expense_name %></td>
      </tr>
      <tr>
        <td>Spent date</td>
        <td><%= @house_expense.spent_date %></td>
      </tr>
      <tr>
        <td>Amount</td>
        <td><%= @house_expense.amount %></td>
      </tr>
      <tr>
        <td>Amount per tenant</td>
        <td>
        <% @house_expense.house_expense_per_tenant.each do |expense_per_tenant| %>
          <%= expense_per_tenant.tenant.name %> : <%= number_with_precision expense_per_tenant.amount, :precision => 2 %>
          <br/>
        <% end %>
        </td>
      </tr>
      <% @house_expense.house_expense_per_tenant.each do |expense_per_tenant| %>
      <tr>
        <td>
          Division factor to <b><%= expense_per_tenant.tenant.name %></b>
        </td>
        <td>
          <%= hidden_field_tag("house_expense_per_tenants_ids[]", expense_per_tenant.id) %>
          <% if expense_per_tenant.tenant_factor.nil? %>
          <%= text_field_tag("house_expense_per_tenants_id" + expense_per_tenant.id.to_s, "1", class: "form-control") %>
          <% else %>
          <%= text_field_tag("house_expense_per_tenants_id" + expense_per_tenant.id.to_s, expense_per_tenant.tenant_factor, class: "form-control") %>
          <% end %>
          
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <div class="form-group">
    <div class="col-sm-offset-3 col-sm-9">
      <%= submit_tag("Update", :class => "btn btn-default") %>
    </div>
  </div>
  <% end %>
  </div>
</div>

app/views/house_expenses/index.html.erb
<p id="notice"><%= notice %></p>

<div class="well well-sm">
  Current account cycle: <%= @current_account_cycle.from_date %> to <%= @current_account_cycle.to_date %>
</div>

<div class="panel panel-primary">
  <div class="panel-heading">Fixed expenses to be paid</div>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Expense</th>
        <th class="text-right">Default amount</th>
        <th>Default payee</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @fixed_expenses.each do |fixed_expense| %>
        <tr>
          <td><%=fixed_expense.expense_name%></td>
          <td class="text-right"><%=fixed_expense.default_amount%></td>
          <td><%=fixed_expense.default_payee.name%></td>
          <td>
          <%= link_to 'Update', update_fixed_expense_path(:fixed_expense_id => fixed_expense.id), method: :get, class: "btn btn-primary" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="panel panel-primary">
  <div class="panel-heading">Expenses for current cycle</div>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Expense</th>
        <th class="text-right">Amount</th>
        <th>Spent by</th>
        <th>Spent date</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @house_expenses.each do |house_expense| %>
        <tr>
          <td><%=house_expense.expense_name%></td>
          <td class="text-right"><%=house_expense.amount%></td>
          <td><%=house_expense.tenant.name%></td>
          <td><%=house_expense.spent_date%></td>
          <td>
          <%= link_to 'Destroy', house_expense, method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-primary" %>
          <%= link_to 'Update factor', edit_division_factor_path(:house_expense_id => house_expense.id), method: :get, class: "btn btn-primary" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to 'New expense', new_house_expense_path, class: "btn btn-primary" %>

app/views/house_expenses/new.html.erb
<h1>New House Expense</h1>

<%= render 'form' %>

<%= link_to 'Back', house_expenses_path %>

app/views/house_expenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tenant:</strong>
  <%= @house_expense.tenant_id %>
</p>

<p>
  <strong>House expense template:</strong>
  <%= @house_expense.house_expense_template_id %>
</p>

<p>
  <strong>Expense name:</strong>
  <%= @house_expense.expense_name %>
</p>

<p>
  <strong>House:</strong>
  <%= @house_expense.house_id %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @house_expense.amount %>
</p>

<p>
  <strong>Spent date:</strong>
  <%= @house_expense.spent_date %>
</p>

<%= link_to 'Edit', edit_house_expense_path(@house_expense) %> |
<%= link_to 'Back', house_expenses_path %>

app/views/house_expenses/update_fixed_expense.html.erb
<h1>Update fixed house expense</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
<%= form_for(@house_expense, :html => {class: "form-horizontal"}) do |f| %>
	<%= f.hidden_field :house_expense_template_id %>
  <% if @house_expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@house_expense.errors.count, "error") %> prohibited this house_expense from being saved:</h2>

      <ul>
      <% @house_expense.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :tenant_id, 'Paid by', class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.collection_select(:tenant_id, @tenants, :id, :name, {}, {:class => 'form-control'}) %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :expense_name, class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_field :expense_name, class: "form-control", "readonly" => 'true' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :amount, class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_field :amount, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :spent_date, class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.date_select :spent_date, {}, {:class => "form-control", :style => "display: inline;width: 32.5%;"} %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :tenant_ids, 'Tenants', class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.collection_check_boxes(:tenant_ids, @tenants, :id, :name) do |b| %>
        <%= b.label do%>
          <%=b.check_box(checked: true) + " " + b.text%>
        <%end%>
        <br/>
      <% end %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-3 col-sm-9">
      <%= f.submit 'Update', :class => "btn btn-default" %>
    </div>
  </div>
<% end %>
  </div>
</div>

<%= link_to 'Back', house_expenses_path %>