config/routes.rb
Rails.application.routes.draw do
  get "house_expenses/account_cycle_summary" => "house_expenses#account_cycle_summary", :as => 'account_cycle_summary'
  resources :house_settings
  resources :house_account_cycles
  get 'sessions/new'

  resources :house_expense_per_tenants
  resources :house_expenses
  resources :house_expense_templates
  resources :recurring_frequencies
  resources :tenants
  resources :houses
  resources :sessions
  
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "house_expenses/update_fixed_expense/:fixed_expense_id" => "house_expenses#update_fixed_expense", :as => 'update_fixed_expense'
  get "house_expenses/edit_division_factor/:house_expense_id" => "house_expenses#edit_division_factor", :as => 'edit_division_factor'
  post "house_expenses/update_division_factor/:house_expense_id" => "house_expenses#update_division_factor", :as => 'update_division_factor'

  root 'houses#index'

end

app/models/house_account_cycle.rb
class HouseAccountCycle < ActiveRecord::Base
	def self.move_to_next_account_cycle(house_id)
		current_cycle = self.get_current_account_cycle(house_id)
		house = House.find(house_id)
		default_cycle_date = house.default_account_cycle_date

		#Move to next month
		new_house_account_cycle = HouseAccountCycle.new
		new_house_account_cycle.house_id = house_id
		new_house_account_cycle.from_date = current_cycle.to_date
		new_house_account_cycle.to_date = current_cycle.to_date + 1.months
		new_house_account_cycle.save

		#Update the house_settings table with new house_account_cycle_id
		house_setting = HouseSetting.get_current_account_cycle_setting(house_id)
		house_setting.setting_value = new_house_account_cycle.id.to_s
		house_setting.save
	end

	def self.get_current_account_cycle(house_id)
		current_account_cycle = HouseAccountCycle.where("id = (select to_number(setting_value,'9') from house_settings where setting_name = 'ACCOUNT_CYCLE') and house_id = ?", house_id).first
	end

	def self.get_last_account_cycle(house_id)
		last_cycle = HouseAccountCycle.where(["id =(select max(house_account_cycle_id) from house_account_summaries where house_id = ?)",house_id]).first
	end
end

app/controllers/house_account_cycles_controller.rb
class HouseAccountCyclesController < ApplicationController
  before_action :set_house_account_cycle, only: [:show, :edit, :update, :destroy]

  # GET /house_account_cycles
  # GET /house_account_cycles.json
  def index
    @house_account_cycles = HouseAccountCycle.all
  end

  # GET /house_account_cycles/1
  # GET /house_account_cycles/1.json
  def show
  end

  # GET /house_account_cycles/new
  def new
    @house_account_cycle = HouseAccountCycle.new
  end

  # GET /house_account_cycles/1/edit
  def edit
  end

  # POST /house_account_cycles
  # POST /house_account_cycles.json
  def create
    @house_account_cycle = HouseAccountCycle.new(house_account_cycle_params)

    respond_to do |format|
      if @house_account_cycle.save
        format.html { redirect_to @house_account_cycle, notice: 'House account cycle was successfully created.' }
        format.json { render :show, status: :created, location: @house_account_cycle }
      else
        format.html { render :new }
        format.json { render json: @house_account_cycle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /house_account_cycles/1
  # PATCH/PUT /house_account_cycles/1.json
  def update
    respond_to do |format|
      if @house_account_cycle.update(house_account_cycle_params)
        format.html { redirect_to @house_account_cycle, notice: 'House account cycle was successfully updated.' }
        format.json { render :show, status: :ok, location: @house_account_cycle }
      else
        format.html { render :edit }
        format.json { render json: @house_account_cycle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /house_account_cycles/1
  # DELETE /house_account_cycles/1.json
  def destroy
    @house_account_cycle.destroy
    respond_to do |format|
      format.html { redirect_to house_account_cycles_url, notice: 'House account cycle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_house_account_cycle
      @house_account_cycle = HouseAccountCycle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def house_account_cycle_params
      params.require(:house_account_cycle).permit(:house_id, :from_date, :to_date)
    end
end

app/helpers/house_account_cycles_helper.rb
module HouseAccountCyclesHelper
end

app/views/house_account_cycles/_form.html.erb
<%= form_for(@house_account_cycle) do |f| %>
  <% if @house_account_cycle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@house_account_cycle.errors.count, "error") %> prohibited this house_account_cycle from being saved:</h2>

      <ul>
      <% @house_account_cycle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :house_id %><br>
    <%= f.number_field :house_id %>
  </div>
  <div class="field">
    <%= f.label :from_date %><br>
    <%= f.date_select :from_date %>
  </div>
  <div class="field">
    <%= f.label :to_date %><br>
    <%= f.date_select :to_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/house_account_cycles/edit.html.erb
<h1>Editing House Account Cycle</h1>

<%= render 'form' %>

<%= link_to 'Show', @house_account_cycle %> |
<%= link_to 'Back', house_account_cycles_path %>

app/views/house_account_cycles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing House Account Cycles</h1>

<table>
  <thead>
    <tr>
      <th>House</th>
      <th>From date</th>
      <th>To date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @house_account_cycles.each do |house_account_cycle| %>
      <tr>
        <td><%= house_account_cycle.house_id %></td>
        <td><%= house_account_cycle.from_date %></td>
        <td><%= house_account_cycle.to_date %></td>
        <td><%= link_to 'Show', house_account_cycle %></td>
        <td><%= link_to 'Edit', edit_house_account_cycle_path(house_account_cycle) %></td>
        <td><%= link_to 'Destroy', house_account_cycle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New House account cycle', new_house_account_cycle_path %>

app/views/house_account_cycles/new.html.erb
<h1>New House Account Cycle</h1>

<%= render 'form' %>

<%= link_to 'Back', house_account_cycles_path %>

app/views/house_account_cycles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>House:</strong>
  <%= @house_account_cycle.house_id %>
</p>

<p>
  <strong>From date:</strong>
  <%= @house_account_cycle.from_date %>
</p>

<p>
  <strong>To date:</strong>
  <%= @house_account_cycle.to_date %>
</p>

<%= link_to 'Edit', edit_house_account_cycle_path(@house_account_cycle) %> |
<%= link_to 'Back', house_account_cycles_path %>