config/routes.rb
Rails.application.routes.draw do
  get "house_expenses/account_cycle_summary" => "house_expenses#account_cycle_summary", :as => 'account_cycle_summary'
  resources :house_settings
  resources :house_account_cycles
  get 'sessions/new'

  resources :house_expense_per_tenants
  resources :house_expenses
  resources :house_expense_templates
  resources :recurring_frequencies
  resources :tenants
  resources :houses
  resources :sessions
  
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "house_expenses/update_fixed_expense/:fixed_expense_id" => "house_expenses#update_fixed_expense", :as => 'update_fixed_expense'
  get "house_expenses/edit_division_factor/:house_expense_id" => "house_expenses#edit_division_factor", :as => 'edit_division_factor'
  post "house_expenses/update_division_factor/:house_expense_id" => "house_expenses#update_division_factor", :as => 'update_division_factor'

  root 'houses#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Houseaccount</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Accounts</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="<%=houses_path%>">Houses<span class="sr-only">(current)</span></a></li>
        <li><a href="<%=tenants_path%>">Tenants</a></li>
        <li><a href="<%=house_expenses_path%>">Expenses</a></li>
      </ul>
      <!--
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      -->
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">User<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Profile</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="<%=log_out_path%>">Logout</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class="panel panel-default">
  <div class="panel-body">
    <%= yield %>
  </div>
</div>
</body>
</html>

app/views/layouts/login.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<div class="panel panel-login">
				<div class="panel-heading">
					<div class="row">
						Login
					</div>
					<hr>
				</div>
				<div class="panel-body">
					<div class="row">
						<div class="col-lg-12">
							<%= yield %>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>